-- TO CREATE A NEW TABLE LOGIN
CREATE TABLE IF NOT EXISTS `login`(
  `id` INT(11) AUTO_INCREMENT NOT NULL,
  `email`  VARCHAR(255) NOT NULL,
   `password` VARCHAR (255) NOT NULL, 
  `user_id` INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY `user_id` (`user_id`) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT FK_user_login FOREIGN KEY(user_id) REFERENCES user(id),
  PRIMARY KEY(id)
  
);  